name: Deploy to ACR

on:
  push:
    branches:
      - main  

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.7

      # - name: Create .env file
      #   run: |
      #     echo "DB_USER=${{ secrets.DB_USER }}" >> $PWD/.env
      #     echo "DB_PASS=${{ secrets.DB_PASS }}" >> $PWD/.env
      #     echo "DB_HOST=${{ secrets.DB_HOST }}" >> $PWD/.env
      #     echo "DB_PORT=${{ secrets.DB_PORT }}" >> $PWD/.env
      #     echo "DB_NAME=${{ secrets.DB_NAME }}" >> $PWD/.env
      
      # - name: List file
      #   run: |
      #    ls -la

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.5.0

      - name: Docker Login
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_URL }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6.5.0
        with:
          file: Dockerfile
          push: true
          tags:  ${{ secrets.REGISTRY_URL }}/${{ secrets.IMAGE_NAME }}:latest
          build-args: |
            DB_USER=${{ secrets.DB_USER }}
            DB_PASS=${{ secrets.DB_PASS }}
            DB_HOST=${{ secrets.DB_HOST }}
            DB_PORT=${{ secrets.DB_PORT }}
            DB_NAME=${{ secrets.DB_NAME }}